const Investment = require('../models/Investment');

// @desc    Get all investments for the authenticated user
// @route   GET /api/investments
// @access  Private
exports.getInvestments = async (req, res) => {
  try {
      const investments = await Investment.find({ user: req.user.id }).sort({ createdAt: -1 });
          res.status(200).json({ success: true, count: investments.length, data: investments });
            } catch (error) {
                console.error('getInvestments error:', error);
                    res.status(500).json({ success: false, message: 'Server error' });
                      }
                      };

                      // @desc    Create a new investment
                      // @route   POST /api/investments
                      // @access  Private
                      exports.createInvestment = async (req, res) => {
                        try {
                            const { name, type, ticker, shares, purchasePrice, purchaseDate, notes } = req.body;
                                if (!name || !type || !purchasePrice) {
                                      return res.status(400).json({ success: false, message: 'Name, type, and purchase price are required' });
                                          }
                                              const investment = await Investment.create({
                                                    user: req.user.id,
                                                          name, type,
                                                                ticker: ticker || null,
                                                                      shares: shares || null,
                                                                            purchasePrice,
                                                                                  purchaseDate: purchaseDate || new Date(),
                                                                                        notes: notes || '',
                                                                                              currentPrice: purchasePrice,
                                                                                                  });
                                                                                                      res.status(201).json({ success: true, data: investment });
                                                                                                        } catch (error) {
                                                                                                            console.error('createInvestment error:', error);
                                                                                                                res.status(500).json({ success: false, message: 'Server error' });
                                                                                                                  }
                                                                                                                  };
                                                                                                                  
                                                                                                                  // @desc    Update an investment
                                                                                                                  // @route   PUT /api/investments/:id
                                                                                                                  // @access  Private
                                                                                                                  exports.updateInvestment = async (req, res) => {
                                                                                                                    try {
                                                                                                                        let investment = await Investment.findById(req.params.id);
                                                                                                                            if (!investment) return res.status(404).json({ success: false, message: 'Investment not found' });
                                                                                                                                if (investment.user.toString() !== req.user.id) return res.status(403).json({ success: false, message: 'Not authorized' });
                                                                                                                                    const allowedUpdates = ['name', 'ticker', 'shares', 'currentPrice', 'notes', 'type'];
                                                                                                                                        const updates = {};
                                                                                                                                            allowedUpdates.forEach((field) => { if (req.body[field] !== undefined) updates[field] = req.body[field]; });
                                                                                                                                                investment = await Investment.findByIdAndUpdate(req.params.id, updates, { new: true, runValidators: true });
                                                                                                                                                    res.status(200).json({ success: true, data: investment });
                                                                                                                                                      } catch (error) {
                                                                                                                                                          console.error('updateInvestment error:', error);
                                                                                                                                                              res.status(500).json({ success: false, message: 'Server error' });
                                                                                                                                                                }
                                                                                                                                                                };
                                                                                                                                                                
                                                                                                                                                                // @desc    Delete an investment
                                                                                                                                                                // @route   DELETE /api/investments/:id
                                                                                                                                                                // @access  Private
                                                                                                                                                                exports.deleteInvestment = async (req, res) => {
                                                                                                                                                                  try {
                                                                                                                                                                      const investment = await Investment.findById(req.params.id);
                                                                                                                                                                          if (!investment) return res.status(404).json({ success: false, message: 'Investment not found' });
                                                                                                                                                                              if (investment.user.toString() !== req.user.id) return res.status(403).json({ success: false, message: 'Not authorized' });
                                                                                                                                                                                  await investment.deleteOne();
                                                                                                                                                                                      res.status(200).json({ success: true, message: 'Investment removed' });
                                                                                                                                                                                        } catch (error) {
                                                                                                                                                                                            console.error('deleteInvestment error:', error);
                                                                                                                                                                                                res.status(500).json({ success: false, message: 'Server error' });
                                                                                                                                                                                                  }
                                                                                                                                                                                                  };
                                                                                                                                                                                                  
                                                                                                                                                                                                  // @desc    Get portfolio summary
                                                                                                                                                                                                  // @route   GET /api/investments/summary
                                                                                                                                                                                                  // @access  Private
                                                                                                                                                                                                  exports.getPortfolioSummary = async (req, res) => {
                                                                                                                                                                                                    try {
                                                                                                                                                                                                        const investments = await Investment.find({ user: req.user.id });
                                                                                                                                                                                                            let totalCost = 0, totalCurrentValue = 0;
                                                                                                                                                                                                                const holdings = investments.map((inv) => {
                                                                                                                                                                                                                      const qty = inv.shares || 1;
                                                                                                                                                                                                                            const cost = inv.purchasePrice * qty;
                                                                                                                                                                                                                                  const current = (inv.currentPrice || inv.purchasePrice) * qty;
                                                                                                                                                                                                                                        const gainLoss = current - cost;
                                                                                                                                                                                                                                              totalCost += cost;
                                                                                                                                                                                                                                                    totalCurrentValue += current;
                                                                                                                                                                                                                                                          return {
                                                                                                                                                                                                                                                                  id: inv._id, name: inv.name, type: inv.type, ticker: inv.ticker,
                                                                                                                                                                                                                                                                          shares: qty, purchasePrice: inv.purchasePrice,
                                                                                                                                                                                                                                                                                  currentPrice: inv.currentPrice || inv.purchasePrice,
                                                                                                                                                                                                                                                                                          cost: parseFloat(cost.toFixed(2)),
                                                                                                                                                                                                                                                                                                  currentValue: parseFloat(current.toFixed(2)),
                                                                                                                                                                                                                                                                                                          gainLoss: parseFloat(gainLoss.toFixed(2)),
                                                                                                                                                                                                                                                                                                                  gainLossPct: cost > 0 ? parseFloat(((gainLoss / cost) * 100).toFixed(2)) : 0,
                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                const totalGainLoss = totalCurrentValue - totalCost;
                                                                                                                                                                                                                                                                                                                                    res.status(200).json({
                                                                                                                                                                                                                                                                                                                                          success: true,
                                                                                                                                                                                                                                                                                                                                                data: {
                                                                                                                                                                                                                                                                                                                                                        totalCost: parseFloat(totalCost.toFixed(2)),
                                                                                                                                                                                                                                                                                                                                                                totalCurrentValue: parseFloat(totalCurrentValue.toFixed(2)),
                                                                                                                                                                                                                                                                                                                                                                        totalGainLoss: parseFloat(totalGainLoss.toFixed(2)),
                                                                                                                                                                                                                                                                                                                                                                                totalGainLossPct: totalCost > 0 ? parseFloat(((totalGainLoss / totalCost) * 100).toFixed(2)) : 0,
                                                                                                                                                                                                                                                                                                                                                                                        holdingsCount: investments.length,
                                                                                                                                                                                                                                                                                                                                                                                                holdings,
                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                            } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                console.error('getPortfolioSummary error:', error);
                                                                                                                                                                                                                                                                                                                                                                                                                    res.status(500).json({ success: false, message: 'Server error' });
                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                      };
                                                                                                                                                                                                                                                                                                                                                                                                                      
